# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:11.6.0

pipelines:
  pull-requests:
    "**":
      - step:
          script:
            - npm install
            - echo "You have passed all tests!. You can proceed to deployment."
